stages:
  preprocess_data:
    cmd: python src/data/preprocess.py
    deps:
    - data/raw/Steel_industry_data.csv
    - src/data/preprocess.py
    outs:
    - data/processed/processed_dataset_X.csv
    - data/processed/processed_dataset_y.csv
  train_model:
    cmd: python src/models/train.py
    deps:
    - data/processed/processed_dataset_X.csv
    - data/processed/processed_dataset_y.csv
    - src/models/train.py
    outs:
    - models/steel_industry_model.keras
  evaluate_model:
    cmd: python src/evaluation/evaluate.py
    deps:
    - data/processed/processed_dataset_X.csv
    - data/processed/processed_dataset_y.csv
    - models/steel_industry_model.keras
    - src/evaluation/evaluate.py
    outs:
    - reports/evaluation.txt
